theme: jekyll-theme-minimal
logo: /assets/pro photo.jpeg
title: Erfan Asadipour, Ph.D.
description: "<b> <em> <font size="12"> Postdoctoral Scholar </font> </em> <br> Florida Solar Energy Center <br> University of Central Florida </b>"
