remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/pro photo.jpeg
title: Erfan Asadipour
description: "<b> <em> Postdoctoral Scholar </em> <br> Florida Solar Energy Center <br> University of Central Florida </b>"
