theme: jekyll-theme-minimal
logo: /assets/pro photo.jpeg
title: Erfan Asadipour, Ph.D.
description: "<b> <em> Postdoctoral Scholar <em> <br> Florida Solar Energy Center</b> <br> University of Central Florida"
